Imagen
Gotensfer/Taller-VII pull request #62
Opened 2023-05-10 00:16 UTC by juanestebanct

Lo primero que se hizo fue crear un sistema donde se pueda guardar las fotos, en estos momentos es un prefab que se tiene que colocar en donde quieran a la hora que se queira guardar una foto.

la forma de expandir mas fotos es simplemente guardando las fotos en recourses 
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/4e875d3b-d76d-46e7-bc65-fc1144595985)
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/b6270f5c-8c2c-4c62-b7d0-f239fed67ffc)
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/95e5e3fe-4c68-4237-9564-fda8ae216fca)

Ahora para la funcionalidad, cuandos e marque una foto, se pasa por un playerpref
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/ab3beab0-5f9c-4192-8c8d-439e4a5bf7ea)

Ahora en player Starts se guarda todas las imagenes en un rpc y ya cuando inicia la partida en un Rpc en Avatarstars  se le dice a todos que guarden la imagen de cada jugador en la sala 

![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/1be0ceaf-d2df-402a-8e34-edd6939aae01)
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/9be94fa8-f293-47e4-95fd-6fdd44c9bcd4)

2023-05-10 00:49 UTC, Gotensfer requested changes
Aun queda pendiente la implementación visual de este sistema junto con la UI.

2023-05-14 04:34 UTC, juanestebanct commented
Se hizo que las imagenes fueran muchos mas amables en la ui por ahora, Si no se seleciona la img se coloca cualqueira random, Se hizo lo de la cara colocando la mascara
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/76631d73-345c-489b-97bc-9d437dd4d229)
Ahi ya en player stast se coloca la imagne de referencia y funciona  Y por medio de un rpc le digo que pase el numero y cambie el material 
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/855dbe27-95b9-4c9c-8b51-73d32918c1f8)
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/4af57e6d-a35c-4e85-bf73-6d2a98061eb1)

2023-05-14 04:34 UTC, SimonOsorioUPB approved these changes

2023-05-14 04:35 UTC, juanestebanct commented
menu mas amable , juli arregla donde carajo va a estar esto la nueva ui, gracias y feliz dia 
![image](https://github.com/Gotensfer/Taller-VII/assets/78618669/a558220a-a8cf-4dc1-9cae-6181534ba955)

2023-05-14 04:48 UTC, Gotensfer approved these changes
Gj!

2023-05-14 04:48 UTC, merged