Grayboxing del mapa y SpawnPoints
Gotensfer/Taller-VII pull request #9
Opened 2023-03-16 00:30 UTC by jaydeeay

En este PR se hace la integración con la rama de development los siguientes elementos:

- Grayboxing del mapa
- SpawnPoints del jugador, la descripción de uso de estos puntos está en el **GDD**, apartado `3. Mecánicas`.

### 1.  GrayBoxing

El greyboxing fue realizado con elementos primitivos teniendo en cuenta lo que el departamento de arte requirió de darle la libertad creativa a ellos de decidir qué elementos iban a ocupar el mapa. Aún así se tenían que tomar elementos escenciales dentro de una oficina para poder contextualizar al jugador.

Estos elementos pueden ser encontrados dentro del editor como `GrayBoxing`
![image](https://user-images.githubusercontent.com/78647931/225472951-63f2d42e-cb1e-453a-ac09-7bc64af6f563.png)

> Por requerimiento de arte se le da prioridad a la verticalidad del mapa, teniendo en cuenta que las anteriores muestras no fueron aprobadas

![image](https://user-images.githubusercontent.com/78647931/225473015-4271f2e3-ed85-4d97-a64b-7be1502aa9e5.png)

> Hay elementos que son ubicados intencionalmente para favorecer mecánicas como agacharse, o saltar

 ### 2. SpawnPoints

Los SpawnPoints se encuentran dentro del editor como `PlayerSpawnPoints` dentro de este elemento se encuentran los puntos de spawn prioritarios o `PriorSpawnPoints` y los puntos de spawn **generales** o sin prioridad. Esta carácterística se puede encontrar descrita en el apartado `3. Mecánicas` del GDD
![image](https://user-images.githubusercontent.com/78647931/225475494-41f9d067-6189-43c7-8952-f027b5806b1d.png)

> Las cápsulas naranjas distinguen los puntos de spawn **prioritarios** y las rojas los puntos generales.

Dentor del editor hay 2 elementos de los cuales 1 es necesario para el desarrollo de la mecánica de spawn, el `SpawnPointDistance` servirá para tener la referencia del cálculo del spawn del jugador.

Quedo atento a cualquier eventualidad, necesidad o aclaración que se requiera con lo que se espera del sistema de spawn ya detallado en el GDD

2023-03-16 01:41 UTC, SimonOsorioUPB requested changes
Falta especificar en el GDD lo de las cápsulas naranjas ya que en las screenshots que hay solo están las rojas. En cuando al PR, por favor organizar la carpeta de materiales en una que esté especificada para el Grayboxing, y organizar las mayúsculas para tener un formato constante en los nombres. De resto todo perfect.
![image](https://user-images.githubusercontent.com/109630052/225487773-97f7e60b-9615-4951-89df-80abc7545402.png)

2023-03-16 01:43 UTC, jaydeeay commented
> 

Solo voy a decir que los materiales sin mayúsculas son culpa de una persona, y no soy yo

2023-03-16 02:14 UTC, Gotensfer commented
@jaydeeay Si el responable del PR sos vos, no estás en ningún derecho de pasar responsabilidades, ojo con eso

2023-03-16 02:16 UTC, Gotensfer requested changes
El Lenguaje usado en el proyecto **siempre debe ser el Inglés**. Esto debe corregirse para seguir protocolos y estándares del proyecto.

![image](https://user-images.githubusercontent.com/77905732/225492318-5f62036b-ddf1-40bc-81dd-33dc196d7cda.png)

2023-03-16 02:18 UTC, jaydeeay commented
> Owner

Alguien dijo que yo pasé responsabilidades a alguien?

2023-03-16 02:18 UTC, jaydeeay commented
> El Lenguaje usado en el proyecto **siempre debe ser el Inglés**. Esto debe corregirse para seguir protocolos y estándares del proyecto.
> 
> ![image](https://user-images.githubusercontent.com/77905732/225492318-5f62036b-ddf1-40bc-81dd-33dc196d7cda.png)

Eso no fue específicado, pero gracias por la aclaración

2023-03-16 02:21 UTC, Gotensfer commented
> > @jaydeeay 
> 
> Solo voy a decir que los materiales sin mayúsculas son culpa de una persona, y no soy yo

Tonces dejá esos comentarios pasivo agresivos por favor, recuerda que si eres el responsable del PR asumes completa responsabilidad de los contenidos de este, por lo que sobra estar haciendo comentarios de este tipo ^^

2023-03-16 03:21 UTC, jaydeeay commented
Cambios realizados

2023-03-17 00:51 UTC, SimonOsorioUPB requested changes
- Falta desactivar cápsulas de medición.
![image](https://user-images.githubusercontent.com/109630052/225781530-4e436b61-1a30-47c6-b2cf-c58335142117.png)

- Desactivarle por favor los colliders a las cápsulas que simbolizan los spawn points, ya que bloquean el paso al hacer pruebas.

- Por este hueco sobre el escritorio, no cabe una cápsula
![image](https://user-images.githubusercontent.com/109630052/225782403-636500ec-82c0-40be-a3e7-5a7f1e242e27.png)

- Este hueco debería ser un poco más ancho, moviendo el "mouse" a la derecha un poco para que el player pueda pasar entre medio, ya que si no, se queda flotando
![image](https://user-images.githubusercontent.com/109630052/225783113-032600b0-0829-4386-8ccf-76d9e5537787.png)

- Por este hueco tampoco puede pasar el player
![image](https://user-images.githubusercontent.com/109630052/225783401-90bf62da-1a60-499b-86f2-bd2f36c62f39.png)

2023-03-17 14:59 UTC, jaydeeay commented
Correcciones realizadas

2023-03-17 15:13 UTC, SimonOsorioUPB approved these changes

2023-03-17 15:26 UTC, merged